name: Build and deploy a container to an Azure Web App

on:
  # https://docs.github.com/ja/actions/using-workflows/events-that-trigger-workflows
  #push:
  #  branches: [ "master" ]
  #  paths:
  #    - 'GitHubActionsSampleApp/**'
  #  #tags:
  #  #  - v1.**
  #pull_request:
  #  types:
  #    - opened
  #  branches: [ "master" ]
  #  paths:
  #    - 'GitHubActionsSampleApp/**'
  workflow_dispatch:

permissions:
      id-token: write
      contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # checkout the repo
      - name: 'Checkout GitHub Action' 
        uses: actions/checkout@v4
    
      - name: 'Sign in via Azure CLI'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        
      - name: Log in to container registry
        run: az acr login -n yuicloudcregist

      - name: Build and push container image to registry
        run: |
          cd GitHubActionsSampleApp
          docker build . -t yuicloudcregist.azurecr.io/githubactionsampleapp:${{ github.sha }}
          docker push yuicloudcregist.azurecr.io/githubactionsampleapp:${{ github.sha }}
    
    #- uses: azure/docker-login@v1
    #  with:
    #    login-server: yuicloudcregist.azurecr.io
    #    username: ${{ secrets.REGISTRY_USERNAME }}
    #    password: ${{ secrets.REGISTRY_PASSWORD }}
    #- run: |
    #    cd GitHubActionsSampleApp
    #    docker build . -t yuicloudcregist.azurecr.io/githubactionsampleapp:${{ github.sha }}
    #    docker push yuicloudcregist.azurecr.io/githubactionsampleapp:${{ github.sha }}
    
      - uses: azure/webapps-deploy@v2
        with:
          app-name: 'yuicloudactionsapp'
          images: 'yuicloudcregist.azurecr.io/githubactionsampleapp:${{ github.sha }}'
    
      - name: Azure logout
        run: |
          az logout
