name: Build and deploy a container to an Azure Web App

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
      id-token: write
      contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - name: 'Checkout GitHub Action' 
      uses: actions/checkout@main
    
    - name: 'Sign in via Azure CLI'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    
    - uses: azure/docker-login@v1
      with:
        login-server: yuicloudcregist.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        cd GitHubActionsSampleApp
        docker build . -t yuicloudcregist.azurecr.io/githubactionsampleapp:${{ github.sha }}
        docker push yuicloudcregist.azurecr.io/githubactionsampleapp:${{ github.sha }}     
      
    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'yuicloudactionsapp'
        images: 'yuicloudcregist.azurecr.io/githubactionsampleapp:${{ github.sha }}'
    
    - name: Azure logout
      run: |
        az logout
