name: Build and deploy a container to an Azure Web App(slot)

on:
  # https://docs.github.com/ja/actions/using-workflows/events-that-trigger-workflows
  push:
    branches: [ "master" ]
    paths:
      - 'GitHubActionsSampleApp/**'
  pull_request:
    types:
      - opened
    branches: [ "master" ]
    paths:
      - 'GitHubActionsSampleApp/**'
  workflow_dispatch:

permissions:
      id-token: write
      contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # checkout the repo
      - name: 'Checkout GitHub Action' 
        uses: actions/checkout@v4
    
      - name: 'Sign in via Azure CLI'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        
      - name: Log in to container registry
        run: az acr login -n yuicloudcregist

      - name: Build and push container image to registry
        run: |
          cd GitHubActionsSampleApp
          docker build . -t yuicloudcregist.azurecr.io/githubactionsampleapp:${{ github.sha }}
          docker push yuicloudcregist.azurecr.io/githubactionsampleapp:${{ github.sha }}

      - name: Azure logout
        run: |
          az logout
          
  dev:
    runs-on: ubuntu-latest

    needs: build
    environment: development
    steps:
      - name: 'Sign in via Azure CLI'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          
      - uses: azure/webapps-deploy@v2
        with:
          app-name: 'yuicloudactionsapp'
          slot-name: staging
          images: 'yuicloudcregist.azurecr.io/githubactionsampleapp:${{ github.sha }}'
          
      - name: Azure logout
        run: |
          az logout
  prd:
    runs-on: ubuntu-latest

    needs: dev
    environment: production
    steps:
      - name: 'Sign in via Azure CLI'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          
      - name: Swap slots
        run: az webapp deployment slot swap -s Production -n yuicloudactionsapp -g rg-container

      - name: Azure logout
        run: |
          az logout
    
